encoding: UTF-8

url: "https://skysense.ag"
title: Skysense
description: AI and Digital Maps for Agriculture

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty

exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - rouge

exclude:
  - .git/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - yarn.lock

defaults:
  - scope:
      path: "assets"
    values:
      image: true
  - scope:
      path: ""
    values:
      image: /assets/img/share.png

collections:
  solutions:
    output: true
  careers:
    output: true